### ISSUE TITLE
I tried this library with my 20x04 LCD and it does not seem to work on the Pico

### ISSUE THREAD

**Issue by VladDob** [cristiancristea00/Pico-I2C-LCD#1]
All I get on the display are the first and third row lighting up. I tested my LCD with an Arduino and it work on that. I read around that it might be an initialization problem. Do you have any suggestions on a way to try to fix my issue?

**Comment by cristiancristea00** [comment]
Hello @VladDob! It looks like an easy-fix problem. The LCD's chip handles display output in a little misleading manner, so you can't output a long string on the LCD and expect it to be wrapped line by line. You have to change the cursor position manually and display a portion of your string. There is an example in the repo for 20x04 displays. Can you try that one and see if it works? If you have further problems, post them here. 😸

**Comment by VladDob** [comment]
I did try the example code provided in the repo. The result is still the same. This is an example of what the LCD is showing. (not my picture and my setup is different, but I get the same result on the LCD)[(https://www.avrfreaks.net/sites/default/files/forum-images/436147-body-1601796708-1.jpg)](https://www.avrfreaks.net/sites/default/files/forum-images/436147-body-1601796708-1.jpg)

**Comment by cristiancristea00** [comment]
Hmmm, that looks like an initialization problem as you mentioned before. My first idea would be to increase the delay value on line 35 in the source file:

```cpp
static constexpr uint16_t DELAY = 600;
```

Maybe try higher values like 1000, 2000, etc.

**Comment by VladDob** [comment]
Tried it but no luck. Changing the DELAY doesn't help. Thank you for the tip though. If you have any other ideas please let me know

**Comment by VladDob** [comment]
If you have any other ideas for me please let me know

**Comment by VladDob** [comment]
I solved my problem. There was **no issue with your library**. The problem was that I didn't ground the pico and the LCD together

**Comment by cristiancristea00** [comment]
Awesome! I'm glad that you solved your problem @VladDob.
